# --- Main Colors ---
background            #131318
foreground            #e5e1e9
cursor                #e5e1e9
cursor_text_color     #131318

selection_background  #464559
selection_foreground  #e4dff9

url_color             #ebb9d0

# --- ANSI Colors ---
color0                #131318
color1                #ffb4ab
color2                #ebb9d0
color3                #c7c4dc
color4                #c4c0ff
color5                #ebb9d0
color6                #c7c4dc
color7                #e5e1e9

color8                #47464f
color9                #93000a
color10               #603b4f
color11               #464559
color12               #434078
color13               #464559
color14               #603b4f
color15               #c8c5d0

# --- Starship Prompt Bubbles ---
color255              #434078
color254              #c4c0ff
color253              #464559
color252              #c7c4dc
color251              #603b4f
color250              #ebb9d0
color249              #93000a
color248              #ffb4ab

color232              #e3dfff
color233              #2d2960
color234              #e4dff9
color235              #302e42
color236              #ffd8e9
color237              #472638
color238              #ffdad6
color239              #690005
color240              #e3dfff

# Matched with unthemed light/dark
color243              #c4c0ff
color244              #ffb4ab
color245              #47464f

# --- UI Elements ---
active_tab_foreground   #2d2960
active_tab_background   #c4c0ff
inactive_tab_foreground #e3dfff
inactive_tab_background #434078

active_border_color     #c4c0ff
inactive_border_color   #928f99

# --- Marks ---
mark1_foreground        #17124a
mark1_background        #e3dfff
mark2_foreground        #1b1a2c
mark2_background        #e4dff9
mark3_foreground        #2f1123
mark3_background        #ffd8e9
